version: "3.9"

services:
  comm-api:
    image: comm-service:latest
    container_name: comm-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      # Telegram Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMINS_TELEGRAM_IDS=${ADMINS_TELEGRAM_IDS}
      - ENABLE_TELEGRAM=true
      # Email Configuration
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@comm-service.local}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      # Security
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1h}
      - MAGIC_LINK_TTL=${MAGIC_LINK_TTL:-300}
      # Service URLs
      - SERVICE_URLS_TRADING=${SERVICE_URLS_TRADING:-http://trading-service:3000}
      - SERVICE_URLS_FINANCIAL=${SERVICE_URLS_FINANCIAL:-http://financial-service:3000}
      - SERVICE_URLS_AI=${SERVICE_URLS_AI:-http://ai-service:3000}
      - SERVICE_URLS_MEMORY=${SERVICE_URLS_MEMORY:-http://memory-service:3000}
      - SERVICE_URLS_GOCARDLESS=${SERVICE_URLS_GOCARDLESS:-http://gocardless-service:3000}
      - SERVICE_URLS_BANK_SYNC=${SERVICE_URLS_BANK_SYNC:-http://bank-sync-service:3000}
      # Webhook Configuration
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT:-5000}
      - WEBHOOK_MAX_RETRIES=${WEBHOOK_MAX_RETRIES:-3}
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - comm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: comm-redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --appendfilename "comm-service.aof"
    networks:
      - comm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  comm-network:
    driver: bridge
    name: comm-network