/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommandAccepted } from '../models';
// @ts-ignore
import type { CommandDispatchRequest } from '../models';
/**
 * CommandsApi - axios parameter creator
 * @export
 */
export const CommandsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Despachar comando a un servicio (con opción de confirmación Sí/No)
         * @param {CommandDispatchRequest} commandDispatchRequest 
         * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1CommandsDispatchPost: async (commandDispatchRequest: CommandDispatchRequest, idempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commandDispatchRequest' is not null or undefined
            assertParamExists('v1CommandsDispatchPost', 'commandDispatchRequest', commandDispatchRequest)
            const localVarPath = `/v1/commands/dispatch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(commandDispatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommandsApi - functional programming interface
 * @export
 */
export const CommandsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommandsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Despachar comando a un servicio (con opción de confirmación Sí/No)
         * @param {CommandDispatchRequest} commandDispatchRequest 
         * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1CommandsDispatchPost(commandDispatchRequest: CommandDispatchRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandAccepted>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1CommandsDispatchPost(commandDispatchRequest, idempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommandsApi.v1CommandsDispatchPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommandsApi - factory interface
 * @export
 */
export const CommandsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommandsApiFp(configuration)
    return {
        /**
         * 
         * @summary Despachar comando a un servicio (con opción de confirmación Sí/No)
         * @param {CommandDispatchRequest} commandDispatchRequest 
         * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1CommandsDispatchPost(commandDispatchRequest: CommandDispatchRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommandAccepted> {
            return localVarFp.v1CommandsDispatchPost(commandDispatchRequest, idempotencyKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommandsApi - interface
 * @export
 * @interface CommandsApi
 */
export interface CommandsApiInterface {
    /**
     * 
     * @summary Despachar comando a un servicio (con opción de confirmación Sí/No)
     * @param {CommandDispatchRequest} commandDispatchRequest 
     * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommandsApiInterface
     */
    v1CommandsDispatchPost(commandDispatchRequest: CommandDispatchRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommandAccepted>;

}

/**
 * CommandsApi - object-oriented interface
 * @export
 * @class CommandsApi
 * @extends {BaseAPI}
 */
export class CommandsApi extends BaseAPI implements CommandsApiInterface {
    /**
     * 
     * @summary Despachar comando a un servicio (con opción de confirmación Sí/No)
     * @param {CommandDispatchRequest} commandDispatchRequest 
     * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommandsApi
     */
    public v1CommandsDispatchPost(commandDispatchRequest: CommandDispatchRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig) {
        return CommandsApiFp(this.configuration).v1CommandsDispatchPost(commandDispatchRequest, idempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }
}

