/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MessageEnqueued } from '../models';
// @ts-ignore
import type { MessageSendRequest } from '../models';
/**
 * MessagesApi - axios parameter creator
 * @export
 */
export const MessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Enviar notificación (Telegram/Email/Auto) con fallback y TTL
         * @param {MessageSendRequest} messageSendRequest 
         * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1MessagesSendPost: async (messageSendRequest: MessageSendRequest, idempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageSendRequest' is not null or undefined
            assertParamExists('v1MessagesSendPost', 'messageSendRequest', messageSendRequest)
            const localVarPath = `/v1/messages/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messageSendRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessagesApi - functional programming interface
 * @export
 */
export const MessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Enviar notificación (Telegram/Email/Auto) con fallback y TTL
         * @param {MessageSendRequest} messageSendRequest 
         * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1MessagesSendPost(messageSendRequest: MessageSendRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageEnqueued>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1MessagesSendPost(messageSendRequest, idempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.v1MessagesSendPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessagesApi - factory interface
 * @export
 */
export const MessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessagesApiFp(configuration)
    return {
        /**
         * 
         * @summary Enviar notificación (Telegram/Email/Auto) con fallback y TTL
         * @param {MessageSendRequest} messageSendRequest 
         * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1MessagesSendPost(messageSendRequest: MessageSendRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageEnqueued> {
            return localVarFp.v1MessagesSendPost(messageSendRequest, idempotencyKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessagesApi - interface
 * @export
 * @interface MessagesApi
 */
export interface MessagesApiInterface {
    /**
     * 
     * @summary Enviar notificación (Telegram/Email/Auto) con fallback y TTL
     * @param {MessageSendRequest} messageSendRequest 
     * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    v1MessagesSendPost(messageSendRequest: MessageSendRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageEnqueued>;

}

/**
 * MessagesApi - object-oriented interface
 * @export
 * @class MessagesApi
 * @extends {BaseAPI}
 */
export class MessagesApi extends BaseAPI implements MessagesApiInterface {
    /**
     * 
     * @summary Enviar notificación (Telegram/Email/Auto) con fallback y TTL
     * @param {MessageSendRequest} messageSendRequest 
     * @param {string} [idempotencyKey] Clave para deduplicar solicitudes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    public v1MessagesSendPost(messageSendRequest: MessageSendRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).v1MessagesSendPost(messageSendRequest, idempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }
}

