/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommandAccepted
 */
export interface CommandAccepted {
    /**
     * 
     * @type {string}
     * @memberof CommandAccepted
     */
    'command_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommandAccepted
     */
    'status'?: CommandAcceptedStatusEnum;
}

export const CommandAcceptedStatusEnum = {
    PendingConfirmation: 'pending_confirmation',
    Queued: 'queued',
    Sent: 'sent'
} as const;

export type CommandAcceptedStatusEnum = typeof CommandAcceptedStatusEnum[keyof typeof CommandAcceptedStatusEnum];


