/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Channel } from './channel';
// May contain unused imports in some cases
// @ts-ignore
import type { CommandDispatchRequestAudit } from './command-dispatch-request-audit';
// May contain unused imports in some cases
// @ts-ignore
import type { Routing } from './routing';

/**
 * 
 * @export
 * @interface CommandDispatchRequest
 */
export interface CommandDispatchRequest {
    /**
     * 
     * @type {string}
     * @memberof CommandDispatchRequest
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof CommandDispatchRequest
     */
    'action': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CommandDispatchRequest
     */
    'args'?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CommandDispatchRequest
     */
    'require_confirmation'?: boolean;
    /**
     * 
     * @type {Channel}
     * @memberof CommandDispatchRequest
     */
    'channel'?: Channel;
    /**
     * 
     * @type {Routing}
     * @memberof CommandDispatchRequest
     */
    'routing'?: Routing;
    /**
     * 
     * @type {CommandDispatchRequestAudit}
     * @memberof CommandDispatchRequest
     */
    'audit'?: CommandDispatchRequestAudit;
}



