/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventInMetrics } from './event-in-metrics';

/**
 * 
 * @export
 * @interface EventIn
 */
export interface EventIn {
    /**
     * 
     * @type {string}
     * @memberof EventIn
     */
    'command_id': string;
    /**
     * 
     * @type {string}
     * @memberof EventIn
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof EventIn
     */
    'status': EventInStatusEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EventIn
     */
    'output'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof EventIn
     */
    'error'?: string;
    /**
     * 
     * @type {EventInMetrics}
     * @memberof EventIn
     */
    'metrics'?: EventInMetrics;
}

export const EventInStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type EventInStatusEnum = typeof EventInStatusEnum[keyof typeof EventInStatusEnum];


