/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HealthStatusDependencies } from './health-status-dependencies';

/**
 * 
 * @export
 * @interface HealthStatus
 */
export interface HealthStatus {
    /**
     * 
     * @type {string}
     * @memberof HealthStatus
     */
    'status'?: HealthStatusStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof HealthStatus
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthStatus
     */
    'service'?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthStatus
     */
    'version'?: string;
    /**
     * 
     * @type {HealthStatusDependencies}
     * @memberof HealthStatus
     */
    'dependencies'?: HealthStatusDependencies;
}

export const HealthStatusStatusEnum = {
    Healthy: 'healthy',
    Unhealthy: 'unhealthy'
} as const;

export type HealthStatusStatusEnum = typeof HealthStatusStatusEnum[keyof typeof HealthStatusStatusEnum];


