/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HealthStatusDependencies
 */
export interface HealthStatusDependencies {
    /**
     * 
     * @type {string}
     * @memberof HealthStatusDependencies
     */
    'redis'?: HealthStatusDependenciesRedisEnum;
}

export const HealthStatusDependenciesRedisEnum = {
    Connected: 'connected',
    Disconnected: 'disconnected'
} as const;

export type HealthStatusDependenciesRedisEnum = typeof HealthStatusDependenciesRedisEnum[keyof typeof HealthStatusDependenciesRedisEnum];


