/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Channel } from './channel';
// May contain unused imports in some cases
// @ts-ignore
import type { Routing } from './routing';
// May contain unused imports in some cases
// @ts-ignore
import type { To } from './to';

/**
 * 
 * @export
 * @interface MessageSendRequest
 */
export interface MessageSendRequest {
    /**
     * 
     * @type {Channel}
     * @memberof MessageSendRequest
     */
    'channel': Channel;
    /**
     * 
     * @type {string}
     * @memberof MessageSendRequest
     */
    'template_key': string;
    /**
     * 
     * @type {string}
     * @memberof MessageSendRequest
     */
    'locale'?: string;
    /**
     * Variables de la plantilla (clave/valor)
     * @type {{ [key: string]: any; }}
     * @memberof MessageSendRequest
     */
    'data': { [key: string]: any; };
    /**
     * 
     * @type {To}
     * @memberof MessageSendRequest
     */
    'to': To;
    /**
     * 
     * @type {boolean}
     * @memberof MessageSendRequest
     */
    'require_confirmation'?: boolean;
    /**
     * 
     * @type {Routing}
     * @memberof MessageSendRequest
     */
    'routing'?: Routing;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MessageSendRequest
     */
    'metadata'?: { [key: string]: any; };
}



