/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Channel } from './channel';

/**
 * 
 * @export
 * @interface MessageEnqueued
 */
export interface MessageEnqueued {
    /**
     * 
     * @type {string}
     * @memberof MessageEnqueued
     */
    'message_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageEnqueued
     */
    'status'?: MessageEnqueuedStatusEnum;
    /**
     * 
     * @type {Channel}
     * @memberof MessageEnqueued
     */
    'channel_selected'?: Channel;
}

export const MessageEnqueuedStatusEnum = {
    Queued: 'queued'
} as const;

export type MessageEnqueuedStatusEnum = typeof MessageEnqueuedStatusEnum[keyof typeof MessageEnqueuedStatusEnum];


