/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Channel } from './channel';

/**
 * 
 * @export
 * @interface Routing
 */
export interface Routing {
    [key: string]: any;

    /**
     * Orden de fallback si falla el canal principal
     * @type {Array<Channel>}
     * @memberof Routing
     */
    'fallback'?: Array<Channel>;
    /**
     * 
     * @type {number}
     * @memberof Routing
     */
    'ttl_seconds'?: number;
}

