/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMethod } from './verification-method';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMode } from './verification-mode';

/**
 * 
 * @export
 * @interface VerificationStarted
 */
export interface VerificationStarted {
    /**
     * 
     * @type {string}
     * @memberof VerificationStarted
     */
    'verification_id'?: string;
    /**
     * 
     * @type {VerificationMethod}
     * @memberof VerificationStarted
     */
    'method'?: VerificationMethod;
    /**
     * 
     * @type {VerificationMode}
     * @memberof VerificationStarted
     */
    'mode'?: VerificationMode;
    /**
     * 
     * @type {string}
     * @memberof VerificationStarted
     */
    'expires_at'?: string;
}



