/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { To } from './to';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMethod } from './verification-method';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMode } from './verification-mode';

/**
 * 
 * @export
 * @interface VerificationStartRequest
 */
export interface VerificationStartRequest {
    /**
     * 
     * @type {VerificationMethod}
     * @memberof VerificationStartRequest
     */
    'method': VerificationMethod;
    /**
     * 
     * @type {string}
     * @memberof VerificationStartRequest
     */
    'purpose': string;
    /**
     * 
     * @type {To}
     * @memberof VerificationStartRequest
     */
    'to': To;
    /**
     * 
     * @type {VerificationMode}
     * @memberof VerificationStartRequest
     */
    'mode': VerificationMode;
    /**
     * 
     * @type {number}
     * @memberof VerificationStartRequest
     */
    'ttl_seconds'?: number;
}



