/* tslint:disable */
/* eslint-disable */
/**
 * Comm-Service API
 * Servicio central de comunicación y orquestación de confirmaciones/comandos entre admin y microservicios (trading, financial, ai, memory). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerificationConfirmRequest
 */
export interface VerificationConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof VerificationConfirmRequest
     */
    'verification_id': string;
    /**
     * 
     * @type {string}
     * @memberof VerificationConfirmRequest
     */
    'token': string;
}

