version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    restart: unless-stopped
    ports:
      - "4873:4873"
    volumes:
      - ./storage:/verdaccio/storage
      - ./conf:/verdaccio/conf
      - ./plugins:/verdaccio/plugins
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PROTOCOL=http
      - VERDACCIO_PUBLIC_URL=http://192.168.1.11:4873/
    networks:
      - npm-registry

networks:
  npm-registry:
    driver: bridge